# Generated by Django 4.1.5 on 2023-01-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Magazyn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategoria', models.CharField(blank=True, max_length=50, null=True)),
                ('produkt', models.CharField(blank=True, max_length=50, null=True)),
                ('ilosc', models.IntegerField(default='0', null=True)),
                ('przyjeta_ilosc', models.IntegerField(blank=True, default='0', null=True)),
                ('przyjete_przez', models.CharField(blank=True, max_length=50, null=True)),
                ('przekazana_ilosc', models.IntegerField(blank=True, default='0', null=True)),
                ('przekazane_przez', models.CharField(blank=True, max_length=50, null=True)),
                ('przekazane_do', models.CharField(blank=True, max_length=50, null=True)),
                ('numer_telefonu', models.CharField(blank=True, max_length=50, null=True)),
                ('utworzone_przez', models.CharField(blank=True, max_length=50, null=True)),
                ('ponownie_zamowic', models.IntegerField(blank=True, default='0', null=True)),
                ('ostatnia_aktualizacja', models.DateTimeField(auto_now=True)),
                ('export_do_CSV', models.BooleanField(default=False)),
            ],
        ),
    ]
