# Generated by Django 4.1.5 on 2023-01-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_mag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='magazyn',
            name='ilosc',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='magazyn',
            name='kategoria',
            field=models.CharField(blank=True, choices=[('Sprzęt Komputerowy ', 'Sprzęt Komputerowy'), ('Meble Biurowe', 'Meble Biurowe'), ('Telefon', 'Telefon'), ('Podzespoły', 'Podzespoły')], max_length=50, null=True),
        ),
    ]
