# Generated by Django 4.1.5 on 2023-01-21 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system_mag', '0002_kategoria_alter_magazyn_ilosc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazyn',
            name='kategoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='system_mag.kategoria'),
            preserve_default=False,
        ),
    ]
